# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 635b0c4565db4aab91cb1a01c373d2f461396a0db5b26f2c1af18d7149dc241d603db86338183cf74067c2424c8acdeee9c6b13612db20b20ad330add023e35f

test:
  secret_key_base: 2cdb719a696560275f526e8b0f27be6fdc7342b1db5853b81c3017102a90d75128d613ac01d33fa6bccbe11b14e104e1f0a0114c2be8e12dd3097e32fd85613e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
